//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBQUIZEntities : DbContext
    {
        public DBQUIZEntities()
            : base("name=DBQUIZEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public DbSet<TBL_QUESTIONS> TBL_QUESTIONS { get; set; }
        public DbSet<TBL_SET_EXAM> TBL_SET_EXAM { get; set; }
        public DbSet<TBL_STUDENT> TBL_STUDENT { get; set; }
        public DbSet<tbl_category> tbl_category { get; set; }
    }
}
