//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STUDENT
    {
        public TBL_STUDENT()
        {
            this.TBL_SET_EXAM = new HashSet<TBL_SET_EXAM>();
        }
    
        public int S_ID { get; set; }
        public string S_NAME { get; set; }
        public string S_PASSWORD { get; set; }
        public string S_IMAGE { get; set; }
    
        public virtual ICollection<TBL_SET_EXAM> TBL_SET_EXAM { get; set; }
    }
}
